# Generated by Django 2.2 on 2021-06-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regapp', '0002_auto_20200523_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Add',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Mob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Sem',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='usn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
